// PRODUCTS
const UPDATE_PRODUCTS = Symbol("UPDATE_PRODUCTS");
const ADD_MORE_PRODUCTS = Symbol("ADD_MORE_PRODUCTS");
const SAVE_PRODUCTS_FILTERS = Symbol("SAVE_PRODUCTS_FILTERS");
const SHOW_LOADING_PRODUCTS = Symbol("SHOW_LOADING_PRODUCTS");
const HIDE_LOADING_PRODUCTS = Symbol("HIDE_LOADING_PRODUCTS");

export {
  // Productos
  UPDATE_PRODUCTS,
  ADD_MORE_PRODUCTS,
  SAVE_PRODUCTS_FILTERS,
  SHOW_LOADING_PRODUCTS,
  HIDE_LOADING_PRODUCTS,
}
